export enum ActionTypes {
  AIRLOCK_OPEN = 'AIRLOCK_OPEN',
  FLOCK_FORM = 'FLOCK_FORM',
  FLOCK_DROP = 'FLOCK_DROP',

  INVITE_SEND = 'INVITE_SEND',

  SCRY_AVAIL_CHATS = 'SCRY_AVAIL_CHATS',
  SCRY_FLOKS = 'SCRY_FLOKS',
  SCRY_SENT_INVITES = 'SCRY_SENT_INVITES',
}
